### ISSUE TITLE
Missing “clear list” function 

### ISSUE THREAD

**Issue by htatla81** [5-star/plugin.video.last_played#12]
Please can you add an option to clear the list for when things get cluttered 

big fan of this tool and part of my daily kodi essentials

**Comment by 5-star** [comment]
I had that in the beginning, I'll try to put it back.

In the meantime you can either remove the entries one by one, ou just delete the json file the the list is kept.
It will be on the addon data directory or on the location specified in the settings.

**Comment by Bassquake** [comment]
> remove the entries one by one

Doing _Remove from list_ doesnt seem to work. It gives no user error but shows something in log. Will do an issue ticket about it.

**Comment by htatla81** [comment]
> > remove the entries one by one
> 
> Doing _Remove from list_ doesnt seem to work. It gives no user error but shows something in log. Will do an issue ticket about it.

Agree doesn’t work in Kodi 19.1

**Comment by Bassquake** [comment]
Just adding that I dont get the delete or history list. Kodi 19.1, Win 10. See screenshot: 
<img width="357" alt="missing" src="https://user-images.githubusercontent.com/5981075/128558398-f06e4588-2e94-4dd0-9959-985d352ba520.PNG">

**Comment by jose1711** [comment]
> Doing Remove from list doesnt seem to work. It gives no user error but shows something in log.

That "something" is:
```
 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.NameError'>
Error Contents: global name 'ListItem' is not defined
Traceback (most recent call last):
File "/home/osmc/.kodi/addons/plugin.video.last_played/addon.py", line 129, in <module>
list_items("*", list_size)
File "/home/osmc/.kodi/addons/plugin.video.last_played/addon.py", line 84, in list_items
li = ListItem(lang(30030))
NameError: global name 'ListItem' is not defined

```
