### ISSUE TITLE
Incompatible with Kodi v19.0 Matrix

### ISSUE THREAD

**Issue by htatla81** [5-star/plugin.video.last_played#13]
When updating Kodi to v19.0 the Last Played add-on is stripped off as incompatible :(

Will you be updating the app so your fans can keep using this very useful add on? 

guessing it requires Python 3 update

**Comment by 5-star** [comment]
Install the latest version 6.0.1, it's V19 compatible. I use it everyday with V19.
It should work equally with Python2 and 3.

**Comment by htatla81** [comment]
Hi 5-Star - thanks yes i upgraded to Matrix v19.0 and it’s working! 
only issue is the add-on thumbnail is gone (changed to default kodi add-on icon)

any way to get it back?

**Comment by 5-star** [comment]
yes, it seems that V19 broke the addon logo, I'll fix it on the next version

**Comment by htatla81** [comment]
Great thank you

perhaps an update logo for 2021? 😊
