### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by ChrisNoCringle30** [5-star/plugin.video.last_played#14]
Hey I'm new to this add-on and I wanted to used it for my kodi. So i copied the link from the installation section of the GitHub. However everytime I try to download from my zip file it shows nothing for me to click on.

**Comment by htatla81** [comment]
If your on kodi v18.9 still try installing GitHub browser and search for 5-star. You will then see last player zip and can install directly

**Comment by ChrisNoCringle30** [comment]
Your right I am still on v18.9. So your saying to insert the github's link into the file manager?

**Comment by htatla81** [comment]
Follow this guide - written for firestick but the links/sources should work for most devices

**Comment by ChrisNoCringle30** [comment]
Thanks. Ok I've followed everything on the guide but I don't see where it says search by username

**Comment by matozelo** [comment]
Hi. Is this working also for Kodi 19? I see that in readme.md is kodi 19 mentioned, but I cant to get it work. I downloaded kodi.zip, copied it to hdd and tried to install from zip, but it did not installed repository.

**Comment by htatla81** [comment]
> Hi. Is this working also for Kodi 19? I see that in readme.md is kodi 19 mentioned, but I cant to get it work. I downloaded kodi.zip, copied it to hdd and tried to install from zip, but it did not installed repository.

Do you get any error msg

**Comment by matozelo** [comment]
Yes, it cannot find zip file.
T26379 Error <general> GetDirectory Error getting zip://sdcard/Download/kodi.zip

**Comment by matozelo** [comment]
I found solution. I downloaded file plugin.video.last_played-master.zip and it worked :)
