### ISSUE TITLE
xbmc.translatePath error in kodi 20

### ISSUE THREAD

**Issue by martyc26** [5-star/plugin.video.last_played#24]
In Kodi 20, the last played addon consistently fails to run.  According to the following post, xbmc.translatePath is removed in Kodi and xbmcvfs.translatePath should be used instead.

https://forum.kodi.tv/showthread.php?tid=361955&pid=3029856#pid3029856

**Comment by 5-star** [comment]
Thanks for the hint

V6.1 released for Kodi 20

**Comment by martyc26** [comment]
didn't see v6.1 from the repo, is there a delay?
