### ISSUE TITLE
kodi.zip not updated with 6.1

### ISSUE THREAD

**Issue by martyc26** [5-star/plugin.video.last_played#25]
Thanks for the hint

V6.1 released for Kodi 20

_Originally posted by @5-star in https://github.com/5-star/plugin.video.last_played/issues/24#issuecomment-1019488289_

**Comment by 5-star** [comment]
Note that last played is:
https://www.starmovies.org/last_played.zip

kodi.zip is the repo, and they are both updated to 6.1
