### ISSUE TITLE
rename repo zip

### ISSUE THREAD

**Issue by htatla81** [5-star/plugin.video.last_played#28]
please can you rename your hosted repo zip as "kodi.zip" is not most helpful when searching for on the device to install :)

([https://www.starmovies.org/kodi.zip](https://www.starmovies.org/kodi.zip))

Sorry this sounds trivial request - you can say "just rename it yourself" but when saving from web directly to a device (eg Fire Stick), its a big task to rename a file to something memorable yourself (separate file browser app needed, no keyboard etc) - so if you could do that for us greatful users it would be much appreciated

you could rename it (perhaps)
**from:** kodi.zip >> **To:** plugin.video.last_played.zip

**Comment by 5-star** [comment]
Done

https://www.starmovies.org/5star.zip
it's the repository

https://www.starmovies.org/last_played.zip
it's the last played addon
