### ISSUE TITLE
Privacy?

### ISSUE THREAD

**Issue by gerroon** [5-star/plugin.video.last_played#3]
Hi

This addons situation on personal privacy is not clear with web access and where things are stored. For instance the readme says
"Play History at 5 Star Movies: The play history can be viewed privately on the www.5star.movies site"

Are you saying that everything I watch is going to be logged at this web site? Is the information logged locally or non-locally? Can you please make this clear so that people realize  that is going on for real.

thanks

**Comment by 5-star** [comment]
Just like trakt it will mark the movies you watch as "Watched". But you need to intentionally choose to do it. Going to the settings and saying that you want to synchronize your watch history. And on a second step selecting the type of videos you want to track.

I use it for myself, so I dont get a movie I already wayched years ago, for instance. And if I dont remember the name of a movie i saw some time ago, the history will remember for me.
