### ISSUE TITLE
Option to clear entire list

### ISSUE THREAD

**Issue by htatla81** [5-star/plugin.video.last_played#32]
Hi - big fan of the last played app

but when will you add the option to wipe the whole list. Very useful when I just want to start clean and add some items in a line up for watching at my convenience etc 

frustrating to only have option to delete one by one

**Comment by 5-star** [comment]
Thank you htatla81,
To clear the full list: Enable the debug in the settings, restart Kodi and open Last Played. At the end of the list there will be an option to clear the list.

**Comment by 5-star** [comment]
> Hi - big fan of the last played app
> 
> but when will you add the option to wipe the whole list. Very useful when I just want to start clean and add some items in a line up for watching at my convenience etc
> 
> frustrating to only have option to delete one by one

Thank you htatla81,
To clear the full list: Enable the debug in the settings, restart Kodi and open Last Played. At the end of the list there will be an option to clear the list.

**Comment by htatla81** [comment]
Thanks the delete history worked - very happy!

FYI when choosing “show history” option I got this error 
![Uploading image.jpg…]()
