### ISSUE TITLE
Play Next/Prev doesn't work from Last Played

### ISSUE THREAD

**Issue by midenok** [5-star/plugin.video.last_played#5]
It is expected that Next/Prev works like if the video was selected from its location.

**Comment by 5-star** [comment]
Maybe this will do what you want
https://forum.kodi.tv/showthread.php?tid=228435

**Comment by midenok** [comment]
How? It's totally different functionality as I can see.

**Comment by 5-star** [comment]
In conjunction with last played. When the replay is ending it suggest the next.

Do you mean the next/prev on the last played list, or on the original location of the file?

The second will not be done because this addon can use any type of source from any addon, even streaming.

**Comment by midenok** [comment]
Next/prev on last played list doesn't make sense at all. When you start some file from this list it should relocate to its location. And then next/prev will work in original source location. And current list will be changed to that location. Recent list should be one-time action: just to relocate to source location and start playing.

> The second will not be done because this addon can use any type of source from any addon, even streaming.

I guess that's not a problem because you can detect type of source and do the above only when possible.
