### ISSUE TITLE
nothing comes up

### ISSUE THREAD

**Issue by cojoMan** [5-star/plugin.video.last_played#7]
I've started and watched for a few minutes a couple of episodes and movies, and nothing shows up in the addon. (Leia beta3)
Am I missing something ?

**Comment by 5-star** [comment]
It was because of leia. The lastest version is now compatible with Kodi 18.

**Comment by cojoMan** [comment]
can you tell me what that version number would be ?
I am using 1.2.2 at the moment - with latest, nightly Leia as of now - and it is still not working...

**Comment by cojoMan** [comment]
That fixed it, thanks !
Well yes, I would like to keep that flag always on "unwatched" in my lists, and this one here to  "all", so if that's what you did, kudos on catching on, I wouldn't have. And thanks !!!
