### ISSUE TITLE
10.8 does not work with Kodi 18.5 Leia anymore

### ISSUE THREAD

**Issue by martinvanwieringen** [5-star/plugin.video.last_played#8]
Hi,

plugin.video.last_played 10.8 does not work with Kodi 18.5 Leia anymore. I tried it on windows and the installation works but I am not able to launch the addon after watching a movie. When I goto the addon the run option cannot be activated.

**Comment by 5-star** [comment]
You're confusing the repository addon 1.0.8 with last played addon (latest version is 1.3.1). 
Install the last played addon using the repository and it will work.

**Comment by martinvanwieringen** [comment]
latest version is 1.3.1 is not available through the repository on Kodi Android TV. Searched  on last and it does not find the last played addon. Where can I download the 1.3.1 zip file so I can install the addon that way?
